This assignment relates to the numpy.random package in Python [2] using Jupyter [5] notebook.

There are four distinct tasks explained in this in Jupyter notebook:

    1. Overall purpose of the Numpy random package.
    2. The use of the “Simple random data” and “Permutations” functions
    3. The use and purpose of at least five “Distributions” functions
    4. The use of seeds in generating pseudorandom numbers


1. Purpose of the Numpy random package

The purpose of the NumPy random package is to generate random numbers as required.  It is highly used in computer programming where generation of random numbers is imperative to many applications.  The numpy.random library contains a variety of random number generators e.g. rand and randint. 

Computing and randomness are not mutually compatible - randomness is counter intuitive in computer programming:

- Computers are deterministic i.e. given a standard input, a standard output is produced. 

- Random numbers are expected to be unpredictable.

- Computers therefore deal with pseudorandom numbers i.e. numbers that behave as if they were random. 

NumPy random number generators are used in a range of distributions that produce sequences of numbers to a given predetermined function.  Examples of usage include statistical sampling, computer simulation, data modelling and gaming.

2.1 Explain the use of the “Simple random data”

Simple random number generators are the most providing random numbers uniformly distributed on an interval. It is used where random integers, floats, bytes etc are required.  It will return a random number with each member of the subset having an equal probability of being chosen.  It is therefore an unbiased representation of the group.  

For example, the rand(num) function generates a float number between 0.0 and 1.0. If () contains no number, just one random number is returned.  If a number of random numbers is required, an array is returned. 

Import Numpy and the random module. As you can see below random floats,integers and bytes are generated as requested.

In [11]:
import numpy as np
import random
np.random.rand()

0.18508207817320688

In [12]:
np.random.rand(3)

array([0.93154087, 0.94773061, 0.4847491 ])

In [13]:
np.random.randint(10)

7

In [14]:
np.random.bytes(5)

b'\xa2\xd2\x90T\xb1'

2.2 Explain the use of the “Permutations” function

The Permutations function changes the order of an arrangement.  Both random.permutation and random.shuffle randomly shuffle elements in an array. Numpy random.shuffle shuffles the elements in an array whereby random.permutation shuffles a copy of the array.

In [15]:
import numpy as np
x = np.array([1,3,14,16,25,29,55])
np.random.shuffle(x)
x

array([ 3, 25, 55,  1, 14, 29, 16])

In [16]:
np.random.permutation(x)

array([25,  3, 16, 55, 14,  1, 29])

3. Explain the use and purpose of at least five “Distributions” functions

4. Explain the use of seeds in generating pseudorandom numbers

Seeds are highly used in computer programming in the generation of pseudo-random numbers.  Computers are not random they are deterministic - they respond with the same answer every time.  How can you use a deterministic computer to produce random numbers?  
- NumPy generates pseudorandom numbers in the submodule random using the Mersenne Twister algorithm. 
- The numbers appear random but are seeded with an initial number.  
- Seeding the pseudorandom number generator results in the same sequence of numbers being generated twice.  Therefore assigning a seed makes random numbers predictable. When the value is reset, the same numbers are output again and again. If a seed is not assigned, NumPy automatically selects a random seed value based on the system's random number generator device or on the clock.

These random numbers are used in a range of distributions.  The value of the seed can be any number but once a seed is assigned the result is the same sequence of random numbers.   

Seeds are very useful as debugging is facilitated by the ability to run the same sequence of random numbers again by starting from the same random seed. However their use in security in cyrptography and security is not recommended as if the seed is known, the code can be broken.

The np.random.seed function provides an input for the pseudo-random number generator in Python.  

Using random.randint, return a random integer and repeat.  Note a different number is generated.

In [7]:
np.random.randint(10)

1

In [8]:
np.random.randint(10)

1

Using a seed, the same answer is returned again and again.

In [9]:
np.random.seed(2)
np.random.randint(10)

8

In [10]:
np.random.seed(2)
np.random.randint(10)

8